package:
  name: cert-manager-openshift-routes
  version: "0.9.0"
  epoch: 0
  description: cert-manager OpenShift route certificate controller
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cert-manager/openshift-routes
      tag: v${{package.version}}
      expected-commit: 9394c9e176032351f96120f23a6f2e94a1a34e0a

  - uses: go/build
    with:
      packages: ./internal/cmd
      output: cert-manager-openshift-routes
      ldflags: |
        -s -w
        -X github.com/cert-manager/openshift-routes/internal/cmd.version=v${{package.version}}
        -X github.com/cert-manager/openshift-routes/internal/cmd.commit=9394c9e176032351f96120f23a6f2e94a1a34e0a

test:
  pipeline:
    - runs: |
        cert-manager-openshift-routes --help
