package:
  name: checkov
  version: "3.2.533"
  epoch: 0
  description: "Static code and composition analysis tool for Infrastructure-as-Code"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py${{vars.python-version}}-pyyaml
      - python-${{vars.python-version}}

vars:
  python-version: "3.12"

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - glibc
      - linux-headers
      - posix-libc-utils
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-pyyaml
      - py${{vars.python-version}}-setuptools
      - py${{vars.python-version}}-wheel
      - python-${{vars.python-version}}
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bridgecrewio/checkov
      tag: ${{package.version}}
      expected-commit: 062b60e4b299bc621f11a01a577274db0805e552

  - runs: |
      PIP_DISABLE_PIP_VERSION_CHECK=1 python${{vars.python-version}} -m pip install \
        --prefix=/usr \
        --root "${{targets.destdir}}" \
        --no-compile \
        .

  - uses: strip

test:
  pipeline:
    - runs: |
        python${{vars.python-version}} -c 'from checkov.version import version; print(version)' | grep -q '${{package.version}}'
