package:
  name: haproxy-3.2
  version: "3.2.21"
  epoch: 0
  description: Reliable, high performance TCP/HTTP load balancer
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - libssl3
      - pcre2
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - linux-headers
      - openssl-dev
      - pcre2-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.haproxy.org/download/3.2/src/haproxy-${{package.version}}.tar.gz
      expected-sha256: 0cb8818a26c5f888e0cb1c40f1b3acb9fb952527d1733f769ce688fedd680339

  - runs: |
      make -j$(nproc) \
        TARGET=linux-glibc \
        USE_GETADDRINFO=1 \
        USE_OPENSSL=1 \
        USE_PCRE2=1 \
        USE_ZLIB=1 \
        PREFIX=/usr \
        SBINDIR=/usr/bin
      make \
        TARGET=linux-glibc \
        USE_GETADDRINFO=1 \
        USE_OPENSSL=1 \
        USE_PCRE2=1 \
        USE_ZLIB=1 \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        DESTDIR="${{targets.destdir}}" \
        install-bin

  - uses: strip

test:
  pipeline:
    - runs: |
        haproxy -vv | grep -q "HAProxy version ${{package.version}}"
