package:
  name: istio-install-cni-1.30
  version: "1.30.2"
  epoch: 0
  description: Istio CNI installer
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 4e213fa7bafe4e932c3b3bb1b97dd022e7bc9583
  - uses: go/build
    with:
      packages: ./cni/cmd/install-cni
      output: install-cni
  - uses: strip
