package:
  name: kured
  version: "1.21.0"
  epoch: 0
  description: "Kubernetes Reboot Daemon"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubereboot/kured
      tag: ${{package.version}}
      expected-commit: 779a3328671312eaef105190467a542c5863e91a

  - uses: go/build
    with:
      packages: ./cmd/kured
      output: kured
      ldflags: |
        -X github.com/kubereboot/kured/pkg/version.Version=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubereboot/kured

test:
  pipeline:
    - runs: |
        kured --version
        kured --help
