name: nginx-prometheus-exporter
description: "NGINX Prometheus exporter — Wolfi rebuild for zero-CVE base"
upstream:
  package: nginx-prometheus-exporter

types:
  default:
    base: wolfi-base
    packages: ["nginx-prometheus-exporter"]
    entrypoint: /usr/bin/nginx-prometheus-exporter

versions:
  "1": {}
