import type { APIRoute } from "astro";

export const GET: APIRoute = ({ site }) => {
  const base = import.meta.env.BASE_URL;
  const origin = site?.origin ?? "https://verity.supply";
  const prefix = `${origin}${base}`;

  const content = `# Supply Chain Compliance — Verity

> Verity signs and attests every container image it publishes. This document details the security controls in place and the compliance frameworks they support.

## Supply Chain Attestations

Every patched image carries five attestations:

1. **cosign signature** — Keyless OIDC via GitHub Actions workflow identity (Sigstore/Fulcio)
2. **SLSA Level 3 build provenance** — Platform-generated by \`actions/attest-build-provenance\`, outside build definition control
3. **CycloneDX SBOM** — Full package inventory generated by Trivy, attached via \`actions/attest-sbom\`
4. **Vulnerability report** — Trivy scan results as in-toto attestation
5. **Rekor transparency log entry** — Tamper-evident, publicly auditable

### Signing Identity

- **Issuer**: \`https://token.actions.githubusercontent.com\`
- **Identity**: \`https://github.com/verity-org/verity/.github/workflows/\`

---

## SLSA Level 3 — Build Integrity

[SLSA v1.0 Specification](https://slsa.dev/spec/v1.0/)

| Level | Requirement | Implementation |
|-------|-------------|----------------|
| Build L1 | Provenance Exists | Every patched image has SLSA provenance attestation generated at build time |
| Build L2 | Hosted Build Platform | All builds on GitHub Actions ephemeral runners, no self-hosted infrastructure |
| Build L3 | Hardened Builds | Provenance generated by \`actions/attest-build-provenance\`, outside build definition control |

---

## Sigstore — Artifact Signing

[Sigstore](https://docs.sigstore.dev/) · [Cosign](https://docs.sigstore.dev/cosign/signing/signing_with_containers/) · [Rekor](https://docs.sigstore.dev/logging/overview/)

### Keyless Signing
All patched images are signed using cosign with keyless OIDC. The GitHub Actions workflow identity token is the signing identity via Fulcio — no long-lived keys to manage or rotate.

### Transparency Log
Every signature is recorded in the Rekor transparency log — tamper-evident, publicly auditable. Signatures are tied to the specific GitHub Actions workflow run.

---

## Software Bill of Materials (SBOM)

[CycloneDX Specification](https://cyclonedx.org/specification/overview/) · [NTIA SBOM](https://www.ntia.gov/page/software-bill-of-materials)

- **Format**: CycloneDX
- **Generator**: Trivy
- **Attachment**: In-toto attestation via \`actions/attest-sbom\`
- **Contents**: All OS packages, libraries, and versions
- **Storage**: GitHub attestation store + OCI registry (travels with the artifact)

---

## Dependency Management

[OpenSSF Best Practices](https://bestpractices.openssf.org/Secure-Software-Development-Fundamentals/en/)

- **Pinned dependencies**: Go modules pinned with cryptographic hashes in \`go.sum\`. GitHub Actions pinned by full commit SHA.
- **Automated updates**: Renovate monitors for dependency updates. Security patches auto-merged for Go minor/patch and Actions patch updates.

---

## Continuous Vulnerability Scanning

[Trivy](https://aquasecurity.github.io/trivy/) · [Copa](https://github.com/project-copacetic/copacetic)

- **Daily scans**: Scheduled workflow at 02:00 UTC re-scans all images
- **Automatic patching**: Copa patches fixable OS-level vulnerabilities in-place
- **PR-driven updates**: New vulnerabilities trigger automatic pull requests

---

## FedRAMP & NIST 800-53 Rev 5

[FedRAMP](https://www.fedramp.gov/) · [NIST SP 800-53 Rev 5](https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final)

| Control | Name | How Verity Meets It |
|---------|------|---------------------|
| SR-3/SR-4 | Supply Chain Provenance | SLSA L3 provenance attestations — verifiable chain from source to artifact |
| SR-11 | Component Authenticity | Cosign OIDC-based signatures verify artifact origin |
| SI-7 | Software & Information Integrity | Signatures and Rekor log entries ensure post-build integrity |
| RA-5 | Vulnerability Monitoring & Scanning | Daily Trivy scans; 30-day report retention for audit evidence |
| CM-14 | Signed Components | All images cryptographically signed before entering registry |
| SA-11 | Developer Testing & Evaluation | CI runs unit tests, linting, and scanning on every PR |

---

## SOC 2 Type II

[AICPA Trust Services Criteria](https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2)

| Criteria | Name | How Verity Meets It |
|----------|------|---------------------|
| CC8.1 | Change Management | All changes via PRs with CI gates; provenance links artifacts to commits |
| CC7.1 | Monitoring & Detection | Daily CVE scans; vulnerability reports retained as workflow artifacts |
| CC6.1 | Logical Access Controls | Scoped \`GITHUB_TOKEN\` with least-privilege; no static keys |
| PI1.4 | Processing Integrity | Cryptographic signatures verify artifacts haven't been altered |

---

## ISO 27001:2022

[ISO/IEC 27001:2022](https://www.iso.org/standard/27001)

| Control | Name | How Verity Meets It |
|---------|------|---------------------|
| A.5.21 | ICT Supply Chain Security | Continuous scanning, pinned dependencies, SBOM attestation |
| A.8.25 | Secure Development Lifecycle | Automated CI gates before any artifact is published |
| A.8.26 | Application Security Requirements | Vulnerability scanning enforces security on every image |
| A.8.30 | Outsourced Development | Third-party images scanned, patched, re-signed under Verity identity |

---

## OWASP ASVS v4

[Application Security Verification Standard v4.0](https://owasp.org/www-project-application-security-verification-standard/)

| Control | Name | How Verity Meets It |
|---------|------|---------------------|
| V14.2 | Dependency | All components from known sources, pinned by hash, auto-updated by Renovate |
| V10.3 | Deployed Application Integrity | Cosign + \`gh attestation verify\` for end-to-end integrity |
| V14.1 | Build & Deploy | Scripted, reproducible builds on ephemeral runners; provenance attestations |

---

## NIST CSF 2.0 & CISA Secure by Design

[NIST Cybersecurity Framework 2.0](https://www.nist.gov/cyberframework) · [CISA Secure by Design](https://www.cisa.gov/securebydesign)

- **GV.SC — Supply Chain Risk Management**: Provenance, signing, SBOM, pinning, and scanning as unified supply chain posture
- **Radical Transparency**: Public vulnerability reports, SBOM on every image, Rekor for public audit

---

## Verification Commands

### Verify cosign signature

\`\`\`bash
cosign verify \\
  --certificate-identity-regexp "https://github.com/verity-org/verity/.github/workflows/" \\
  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \\
  ghcr.io/verity-org/grafana/grafana:11.6.0-patched
\`\`\`

### Verify build provenance

\`\`\`bash
gh attestation verify \\
  oci://ghcr.io/verity-org/grafana/grafana:11.6.0-patched \\
  --owner verity-org
\`\`\`

---

## Build Pipeline Overview

1. **Discover** — Container images enumerated from \`values.yaml\`
2. **Scan** — Trivy scans each image for OS-level vulnerabilities
3. **Patch** — Copa patches fixable CVEs in-place on ephemeral runners
4. **Push** — Patched images pushed to GHCR
5. **Sign** — Cosign signs via keyless OIDC; signatures logged in Rekor
6. **Attest** — SLSA provenance, CycloneDX SBOM, and vulnerability reports attached

---

[Full LLM Reference](${prefix}llms-full.txt) · [Browse Catalog](${prefix}) · [GitHub](https://github.com/verity-org/verity)
`;

  return new Response(content.trim() + "\n", {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
};
